@startuml 

skin rose 
  
:Aluno: 

:Secretaria da universidade: as Uni 

:Professor: 


Aluno --> (Visualizar disciplinas) 

(Visualizar disciplinas) <. (Matricular em disciplina) : extends

(Visualizar disciplinas) <. (Cancelar matricula na disciplina) : extends

(Cancelar matricula na disciplina) .> (Notificar sistema de cobranca) : include

(Matricular em disciplina) .> (Notificar sistema de cobranca) : include



Professor --> (Visualizar alunos matriculados) 
  

Uni --> (Gerar curriculo) 



  

@enduml 
